#!/bin/sh
mkdir -p ~/.ssh

>>~/.ssh/id_rsa.pub cat <<EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDYQRb+AOkJBatJiWJuGwLX7fT84fRvaKE8gbtyt8V37d3hS6/p9uzgzgT7v9AVsCA9YCOEs0wmbBxZgGrzoF657X5LbOBNPRo9Omt0hSTzx/1JkvPt4a/2vzjp5Rzw+IwF9+LOEnPcQjZNLLXCJxofoUitD2w6M83e06O4VTQlVKk9P50L1SFBtUHPT88IJ4OnIEMCBHik/zka5nG7p98prxeGV+jGL+2Axuq2MavEiqHeOtsLk9CUkvzsio/1jD8y1ZssR+Hdhj6k746KZl+qjY20ZWESuHYTt6R6jkKWMOvGW44AjPFOPP1cQPtrWgffNt5HnQJRDSUnniZT3LR kvin@J1900
EOF
PRI_KEY=$(echo $PRI_KEY | tr ' ' '\n')
>>~/.ssh/id_rsa cat <<EOF
-----BEGIN RSA PRIVATE KEY-----
$PRI_KEY
-----END RSA PRIVATE KEY-----
EOF

>>~/.ssh/authorized_keys cat <<EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSA3GJHgNCNIHNvOUNwd83O7us7l2ZjTGlSvOiRj75eIBRjncoUKM2O/CvAnKNsP8aDD/KiHEGbLvYQWYe8E6l9bsWqwojwnXtulxlq7PCcws+aFfRqgFMx5emiYSSmOAUYxxCTAE4YSh1e/4mUXG78C64X8wnErjZpmp2h/d4cez1UTXBD8A7oMTLoSlIn9XOxcDBeVTmj+SOdExMqpUbBXwh5aCrfOXg3FLD7JYXiu01h5EErgsqs5uwz6ndR7W0R5vqw9sQ5B+dooGW5m47ofoNh/FNeu0Zvw7ZfB/OVzrXC6+Srq8dI9YwMwbo8plddFhMni3EwZ1oexmNQ6dZ kvin@J1900
EOF

chmod 600 ~/.ssh/id_rsa
chmod 600 ~/.ssh/authorized_keys

echo 'PubkeyAuthentication yes' | sudo tee -a /etc/ssh/sshd_config

echo 'vsts:123456' | sudo chpasswd

sudo mkdir -p /run/sshd
sudo /usr/sbin/sshd

./merino --no-auth > /dev/null 2>&1 &
ssh -o StrictHostKeyChecking=no -tt -R1081:localhost:1080 -R1822:localhost:22 kvin@home.kvin.wang
